/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Catalogo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import sistemacontable.claseconexion;

/**
 *
 * @author Agry
 */
public class MDI extends javax.swing.JFrame {

    DefaultTableModel model;
    Connection Con;
    Statement St;
    DefaultMutableTreeNode cat;

    /**
     * Creates new form MDI
     */
    public MDI() {

        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

        actualizarcatalogo();

    }

    private void actualizarcatalogo() {
        cat = new DefaultMutableTreeNode("Catalogo");
        DefaultMutableTreeNode ACTIVO = new DefaultMutableTreeNode("ACTIVO");
        DefaultMutableTreeNode PASIVO = new DefaultMutableTreeNode("PASIVO");
        DefaultMutableTreeNode CAPITAL = new DefaultMutableTreeNode("CAPITAL");
        DefaultMutableTreeNode INGRESOS = new DefaultMutableTreeNode("INGRESOS");
        DefaultMutableTreeNode GASTOS = new DefaultMutableTreeNode("GASTOS");
        cat.add(ACTIVO);
        cat.add(PASIVO);
        cat.add(CAPITAL);
        cat.add(INGRESOS);
        cat.add(GASTOS);

        ArrayList<Catalogo> cuentas = new Catalogo().consultar();
        for (Catalogo cuenta : cuentas) {
            /*  DefaultMutableTreeNode cta = new DefaultMutableTreeNode();
             cta.setUserObject(cuenta.getCuenta());
             cat.add(cta);*/
            System.out.println(cuenta.getNCuenta().substring(0, 1));
            if (cuenta.getNCuenta().length() != 1) {
                switch (cuenta.getNCuenta().substring(0, 1)) {
                    case "1":
                        ACTIVO.add(new DefaultMutableTreeNode("[" + cuenta.getNCuenta() + "] " + " [" + cuenta.getCuenta() + "]"));
                        break;
                    case "2":
                        PASIVO.add(new DefaultMutableTreeNode("[" + cuenta.getNCuenta() + "] " + " [" + cuenta.getCuenta() + "]"));
                        break;
                    case "3":
                        CAPITAL.add(new DefaultMutableTreeNode("[" + cuenta.getNCuenta() + "] " + " [" + cuenta.getCuenta() + "]"));
                        break;
                    case "4":
                        INGRESOS.add(new DefaultMutableTreeNode("[" + cuenta.getNCuenta() + "] " + " [" + cuenta.getCuenta() + "]"));
                        break;
                    case "5":
                        GASTOS.add(new DefaultMutableTreeNode("[" + cuenta.getNCuenta() + "] " + " [" + cuenta.getCuenta() + "]"));
                        break;
                }
            }
        }
        DefaultTreeModel modeloArbol = new DefaultTreeModel(cat);
        this.Catalogo.setModel(modeloArbol);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Catalogo = new javax.swing.JTree();
        jPanel5 = new javax.swing.JPanel();
        txtnuevo = new javax.swing.JTextField();
        txtcuenta = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnnuevacuenta = new javax.swing.JButton();
        btneditarcuenta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btneliminarcuenta = new javax.swing.JButton();
        btnguardarcambios = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estructura de Catalogo"));

        Catalogo.setFont(new java.awt.Font("Mangal", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(Catalogo);

        jPanel4.add(jScrollPane1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento Catalogo"));

        txtnuevo.setText("jTextField1");
        txtnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnuevoActionPerformed(evt);
            }
        });

        txtcuenta.setText("jTextField2");
        txtcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcuentaActionPerformed(evt);
            }
        });

        txttipo.setText("jTextField3");

        jLabel1.setFont(new java.awt.Font("Mangal", 0, 11)); // NOI18N
        jLabel1.setText("Ncuenta:");

        btnnuevacuenta.setFont(new java.awt.Font("Mangal", 0, 11)); // NOI18N
        btnnuevacuenta.setText("Nueva Cuenta");
        btnnuevacuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevacuentaActionPerformed(evt);
            }
        });

        btneditarcuenta.setFont(new java.awt.Font("Mangal", 0, 11)); // NOI18N
        btneditarcuenta.setText("Editar Cuenta");
        btneditarcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarcuentaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Mangal", 0, 11)); // NOI18N
        jLabel2.setText("Cuenta");

        jLabel3.setFont(new java.awt.Font("Mangal", 0, 11)); // NOI18N
        jLabel3.setText("Tipo");

        btneliminarcuenta.setFont(new java.awt.Font("Mangal", 0, 11)); // NOI18N
        btneliminarcuenta.setText("Eliminar Cuenta");
        btneliminarcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarcuentaActionPerformed(evt);
            }
        });

        btnguardarcambios.setFont(new java.awt.Font("Mangal", 0, 11)); // NOI18N
        btnguardarcambios.setText("Guardar Cambios");
        btnguardarcambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarcambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnguardarcambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btneliminarcuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btneditarcuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnnuevacuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnuevo))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnnuevacuenta)
                .addGap(18, 18, 18)
                .addComponent(btneditarcuenta)
                .addGap(18, 18, 18)
                .addComponent(btneliminarcuenta)
                .addGap(18, 18, 18)
                .addComponent(btnguardarcambios)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5);

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Operacion\n"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Controles"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevacuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevacuentaActionPerformed

    }//GEN-LAST:event_btnnuevacuentaActionPerformed

    private void btneliminarcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarcuentaActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_btneliminarcuentaActionPerformed

    private void btnguardarcambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarcambiosActionPerformed
        // TODO add your handling code here:
        Catalogo ct = new Catalogo(txtnuevo.getText(), txtcuenta.getText(), txttipo.getText());
        ct.insertar();
        actualizarcatalogo();
    }//GEN-LAST:event_btnguardarcambiosActionPerformed

    private void txtnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnuevoActionPerformed
        // TODO add your handling code here:
        txtnuevo.setText("");
        txtcuenta.setText("");
        txttipo.setText("");

    }//GEN-LAST:event_txtnuevoActionPerformed

    private void txtcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcuentaActionPerformed

    private void btneditarcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarcuentaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btneditarcuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree Catalogo;
    private javax.swing.JButton btneditarcuenta;
    private javax.swing.JButton btneliminarcuenta;
    private javax.swing.JButton btnguardarcambios;
    private javax.swing.JButton btnnuevacuenta;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcuenta;
    private javax.swing.JTextField txtnuevo;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
